Release v6.0.0 (#1614)
This PR was opened by the [Changesets
release](https://github.com/changesets/action) GitHub action. When
you're ready to do a release, you can merge this and the packages will
be published to npm automatically. If you're not ready to do a release
yet, that's fine, whenever you add more changesets to main, this PR will
be updated.


# Releases
## @comet/admin@6.0.0

### Major Changes

-   298b63b7: `FinalForm`: Remove default `onAfterSubmit` implementation

In most cases the default implementation is not wanted anymore. When
upgrading, an empty
function override of `onAfterSubmit` can be removed as it is no longer
necessary.

    To get back the old behavior use the following in application code:

    ```tsx
    const stackApi = React.useContext(StackApiContext);
    const editDialog = React.useContext(EditDialogApiContext);

    // ...

    <FinalForm
        onAfterSubmit={() => {
            stackApi?.goBack();
            editDialog?.closeDialog({ delay: true });
        }}
    >
    ```

- 0d768540: `FinalForm`: Don't handle sync submit differently than async
submit

- 62779124: `FinalFormContext`: Change the signatures of
`shouldScrollToField`, `shouldShowFieldError` and
`shouldShowFieldWarning` in `FinalFormContext` to match the
corresponding methods in `Field`

    The API in `FinalFormContext` was changed from

    ```tsx
    // ❌
    export interface FinalFormContext {
shouldScrollToField: ({ fieldMeta }: { fieldMeta: FieldMetaState<any> })
=> boolean;
shouldShowFieldError: ({ fieldMeta }: { fieldMeta: FieldMetaState<any>
}) => boolean;
shouldShowFieldWarning: ({ fieldMeta }: { fieldMeta: FieldMetaState<any>
}) => boolean;
    }
    ```

    to

    ```tsx
    // ✅
    export interface FinalFormContext {
shouldScrollToField: (fieldMeta: FieldMetaState<any>) => boolean;
shouldShowFieldError: (fieldMeta: FieldMetaState<any>) => boolean;
shouldShowFieldWarning: (fieldMeta: FieldMetaState<any>) => boolean;
    }
    ```

Now the corresponding methods in `Field` and `FinalFormContext` have the
same signature.

### Minor Changes

- 921f6378: Add `helperText` prop to `Field` and `FieldContainer` to
provide additional information

### Patch Changes

-   Updated dependencies [76e50aa8]
-   Updated dependencies [a525766c]
    -   @comet/admin-icons@6.0.0

## @comet/admin-icons@6.0.0

### Major Changes

- a525766c: Remove deprecated icons `Betrieb`, `LogischeFilter`, `Pool`,
`Pool2`, `StateGreen`, `StateGreenRing`, `StateOrange`,
`StateOrangeRing`, `StateRed`, `StateRedRing`, `Vignette1` and
`Vignette2`.

### Patch Changes

-   76e50aa8: Fix broken `Logout` icon

## @comet/cms-admin@6.0.0

### Major Changes

-   d20f59c0: Enhance CronJob module

    -   Show latest job run on `CronJobsPage`
    -   Add option to manually trigger cron jobs to `CronJobsPage`
    -   Add subpage to `CronJobsPage` that shows all job runs

Warning: Only include this module if all your users should be able to
trigger cron jobs manually or you have sufficient access control in
place.

    Includes the following breaking changes:

- Rename `JobStatus` to `KubernetesJobStatus` to avoid naming conflicts
    -   Rename `BuildRuntime` to `JobRuntime`

-   d86d5a90: Make sites config generic

The sites config was previously assumed to be `Record<string,
SiteConfig>`.
However, as the sites config is solely used in application code, it
could be of any shape.
Therefore, the `SitesConfigProvider` and `useSitesConfig` are made
generic.
    The following changes have to be made in the application:

    1.  Define the type of your sites config

        Preferably this should be done in `config.ts`:

        ```diff
        export function createConfig() {
            // ...

            return {
                ...cometConfig,
                apiUrl: environmentVariables.API_URL,
                adminUrl: environmentVariables.ADMIN_URL,
+ sitesConfig: JSON.parse(environmentVariables.SITES_CONFIG) as
SitesConfig,
            };
        }

        + export type SitesConfig = Record<string, SiteConfig>;
        ```

    2.  Use the type when using `useSitesConfig`

        ```diff
        - const sitesConfig = useSitesConfig();
        + const sitesConfig = useSitesConfig<SitesConfig>();
        ```

3. Optional: Remove type annotation from
`ContentScopeProvider#resolveSiteConfigForScope` (as it's now inferred)

        ```diff
- resolveSiteConfigForScope: (configs: Record<string, SiteConfig>,
scope: ContentScope) => configs[scope.domain],
+ resolveSiteConfigForScope: (configs, scope: ContentScope) =>
configs[scope.domain],
        ```

### Minor Changes

- 0f814c5e: Add `MasterMenu` and `MasterMenuRoutes` components which
both take a single data structure to define menu and routes.

### Patch Changes

-   Updated dependencies [921f6378]
-   Updated dependencies [76e50aa8]
-   Updated dependencies [298b63b7]
-   Updated dependencies [803f5045]
-   Updated dependencies [a525766c]
-   Updated dependencies [0d768540]
-   Updated dependencies [62779124]
    -   @comet/admin@6.0.0
    -   @comet/admin-icons@6.0.0
    -   @comet/admin-rte@6.0.0
    -   @comet/admin-date-time@6.0.0
    -   @comet/blocks-admin@6.0.0
    -   @comet/admin-theme@6.0.0

## @comet/cms-api@6.0.0

### Major Changes

-   d20f59c0: Enhance CronJob module

    -   Show latest job run on `CronJobsPage`
    -   Add option to manually trigger cron jobs to `CronJobsPage`
    -   Add subpage to `CronJobsPage` that shows all job runs

Warning: Only include this module if all your users should be able to
trigger cron jobs manually or you have sufficient access control in
place.

    Includes the following breaking changes:

- Rename `JobStatus` to `KubernetesJobStatus` to avoid naming conflicts
    -   Rename `BuildRuntime` to `JobRuntime`

-   b3ceaef1: Replace `ContentScopeModule` with `UserPermissionsModule`

    Breaking changes:

    -   `ContentScopeModule` has been removed
- `canAccessScope` has been moved to `AccessControlService` and
refactored into `isAllowed`
- `contentScopes` and `permissions` fields have been added to
`CurrentUser` object
- `role` and `rights` fields has been removed from `CurrentUser` object
    -   `AllowForRole` decorator has been removed
    -   Rename `SubjectEntity` decorator to `AffectedEntity`
- Add `RequiredPermission` decorator and make it mandatory when using
`UserPermissionsModule`

### Patch Changes

-   @comet/blocks-api@6.0.0

## @comet/eslint-config@6.0.0

### Major Changes

-   72f98c7a: Enable `import/newline-after-import` rule by default
-   47eb81c6: Enable `no-other-module-relative-import` rule by default

### Patch Changes

-   @comet/eslint-plugin@6.0.0

## @comet/admin-color-picker@6.0.0

### Patch Changes

-   Updated dependencies [921f6378]
-   Updated dependencies [76e50aa8]
-   Updated dependencies [298b63b7]
-   Updated dependencies [a525766c]
-   Updated dependencies [0d768540]
-   Updated dependencies [62779124]
    -   @comet/admin@6.0.0
    -   @comet/admin-icons@6.0.0

## @comet/admin-date-time@6.0.0

### Patch Changes

-   Updated dependencies [921f6378]
-   Updated dependencies [76e50aa8]
-   Updated dependencies [298b63b7]
-   Updated dependencies [a525766c]
-   Updated dependencies [0d768540]
-   Updated dependencies [62779124]
    -   @comet/admin@6.0.0
    -   @comet/admin-icons@6.0.0

## @comet/admin-react-select@6.0.0

### Patch Changes

-   Updated dependencies [921f6378]
-   Updated dependencies [298b63b7]
-   Updated dependencies [0d768540]
-   Updated dependencies [62779124]
    -   @comet/admin@6.0.0

## @comet/admin-rte@6.0.0

### Patch Changes

- 803f5045: Retain headings 4 - 6, blockquote and strikethrough
formatting when copying from one RTE to another
-   Updated dependencies [76e50aa8]
-   Updated dependencies [a525766c]
    -   @comet/admin-icons@6.0.0

## @comet/admin-theme@6.0.0

### Patch Changes

-   Updated dependencies [76e50aa8]
-   Updated dependencies [a525766c]
    -   @comet/admin-icons@6.0.0

## @comet/blocks-admin@6.0.0

### Patch Changes

-   Updated dependencies [921f6378]
-   Updated dependencies [76e50aa8]
-   Updated dependencies [298b63b7]
-   Updated dependencies [a525766c]
-   Updated dependencies [0d768540]
-   Updated dependencies [62779124]
    -   @comet/admin@6.0.0
    -   @comet/admin-icons@6.0.0

## @comet/admin-babel-preset@6.0.0



## @comet/blocks-api@6.0.0



## @comet/cli@6.0.0



## @comet/eslint-plugin@6.0.0



## @comet/cms-site@6.0.0

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>