Version Packages (#2369)
This PR was opened by the [Changesets
release](https://github.com/changesets/action) GitHub action. When
you're ready to do a release, you can merge this and the packages will
be published to npm automatically. If you're not ready to do a release
yet, that's fine, whenever you add more changesets to main, this PR will
be updated.


# Releases
## @comet/admin@7.1.0

### Minor Changes

- 04844d39e: Adjust the alignment and spacing of the label, the input,
and child fields inside `FieldContainer` and `Field`

- c0488eb84: Use `FeedbackButton` in `DeleteDialog` of `CrudContextMenu`

This provides the user with feedback about the current status of the
delete action.

- c1ab2b340: Add `CheckboxListField` component to make it easier to
create checkbox lists in forms

    You can now do:

    ```tsx
    <CheckboxListField
        label="Checkbox List"
        name="checkboxList"
        fullWidth
        options={[
            {
                label: "Option One",
                value: "option-one",
            },
            {
                label: "Option Two",
                value: "option-two",
            },
        ]}
    />
    ```

    instead of:

    ```tsx
    <FieldContainer label="Checkbox List" fullWidth>
<CheckboxField name="checkboxList" label="Checkbox one"
value="checkbox-one" />
<CheckboxField name="checkboxList" label="Checkbox two"
value="checkbox-two" />
    </FieldContainer>
    ```

- 99a1f0ae6: Add `RadioGroupField` component to make it easier to create
radio group fields in forms

    You can now do:

    ```tsx
    <RadioGroupField
        label="Radio"
        name="radio"
        fullWidth
        options={[
            {
                label: "Option One",
                value: "option-one",
            },
            {
                label: "Option Two",
                value: "option-two",
            },
        ]}
    />
    ```

    instead of:

    ```tsx
    <FieldContainer label="Radio" fullWidth>
        <Field name="radio" type="radio" value="option-one">
{(props) => <FormControlLabel label="Option One"
control={<FinalFormRadio {...props} />} />}
        </Field>
        <Field name="radio" type="radio" value="option-two">
{(props) => <FormControlLabel label="Option Two"
control={<FinalFormRadio {...props} />} />}
        </Field>
    </FieldContainer>
    ```

- edf14d066: Add the `disableSlider` prop to `FinalFormRangeInput` to
disable the slider and only show the input fields

    ```tsx
<Field name="numberRange" label="Range Input"
component={FinalFormRangeInput} min={0} max={100} disableSlider />
    ```

- c050f2242: Make the separator of `FinalFormRangeInput` overridable
using the `separator` prop and change the default to the string "to"

    Example to restore the previous separator:

    ```tsx
<Field name="numberRange" label="Range Input"
component={FinalFormRangeInput} min={0} max={100} separator="-" />
    ```

### Patch Changes

- dfc4a7fff: Adjust the spacing of `FinalFormRangeInput` to align with
other inputs

- 39ab15616: Fix the behavior of `FinalFormRangeInput` when the `min`
and `max` values are inverted

Previously, e.g., when the `min` value was changed to something greater
than the `max` value, the `min` value would be set to the same as the
max value.
    Now, the `min` and `max` values are swapped.

- 2b68513be: Fix the alignment of the input inside `FieldContainer` and
`Field` when there is no label with `variant="horizontal"`

- 374f383ba: Increase `Toolbar` padding left and right from 10px to 20px

-   Updated dependencies [3adf5fecd]

-   Updated dependencies [04844d39e]

-   Updated dependencies [c90ae39d4]

-   Updated dependencies [b1bbd6a0c]
    -   @comet/admin-theme@7.1.0
    -   @comet/admin-icons@7.1.0

## @comet/admin-icons@7.1.0

### Minor Changes

-   b1bbd6a0c: Export a type for all icon names: `IconName`

## @comet/admin-theme@7.1.0

### Minor Changes

- 04844d39e: Adjust the alignment and spacing of the label, the input,
and child fields inside `FieldContainer` and `Field`

### Patch Changes

-   3adf5fecd: Remove unnecessary padding of DataGrid rows
- c90ae39d4: Fix spacing between page number and chevron icon in the
pagination select of `DataGrid`
-   Updated dependencies [b1bbd6a0c]
    -   @comet/admin-icons@7.1.0

## @comet/blocks-admin@7.1.0

### Minor Changes

-   1fe10e883: Add `maxVisibleBlocks` option to `createBlocksBlock`
-   e53f4ce06: OneOfBlock: Remove label for the type field

The label was unnecessary and occasionally caused UI problems when
having two labels next each other.

### Patch Changes

- 2253a1d00: createListBlock: Don't show the minimum visible blocks
tooltip when the option isn't used
- 6be41b668: Fix color for visible icon button in `ListBlock` and
`ColumnsBlock`
-   Updated dependencies [04844d39e]
-   Updated dependencies [dfc4a7fff]
-   Updated dependencies [b1bbd6a0c]
-   Updated dependencies [c0488eb84]
-   Updated dependencies [39ab15616]
-   Updated dependencies [c1ab2b340]
-   Updated dependencies [99a1f0ae6]
-   Updated dependencies [edf14d066]
-   Updated dependencies [2b68513be]
-   Updated dependencies [374f383ba]
-   Updated dependencies [c050f2242]
    -   @comet/admin@7.1.0
    -   @comet/admin-icons@7.1.0

## @comet/cms-admin@7.1.0

### Minor Changes

- 7410aae83: Add new `FileUploadField` component for uploading files in
forms using the `FileUploadsModule`

-   945ba8725: Add `icon` prop to `DashboardWidgetRoot`

-   9a8098488: Rework `EditImageDialog`

    Changes

    -   Increase image size
    -   Add hover effects for focal points
    -   Add "Open in DAM" button

Note: This feature only works if the `DependenciesConfig` is configured
for `DamFile`:

        ```diff
        // App.tsx

        <DependenciesConfigProvider
            entityDependencyMap={{
        +       DamFile: createDamFileDependency(),
                // ...
            }}
        >
        ```

- 91b154b06: Make the details and creator/author fields optional when
using the DAM license feature

### Patch Changes

- 7dabe8d11: Fix the content scope indicator on the `EditFile` page if
DAM scoping is disabled

- 452a12a3c: Change text color of `FilePreview` action buttons to white

Previously, the text was invisible because it was black on a black
background.

-   bbb753600: Fix false positives in `resolveHasSaveConflict` check

    The check occasionally failed due to rounding errors.
    This is fixed by rounding to full seconds before checking.

-   Updated dependencies [3adf5fecd]

-   Updated dependencies [04844d39e]

-   Updated dependencies [2253a1d00]

-   Updated dependencies [dfc4a7fff]

-   Updated dependencies [1fe10e883]

-   Updated dependencies [c90ae39d4]

-   Updated dependencies [b1bbd6a0c]

-   Updated dependencies [c0488eb84]

-   Updated dependencies [e53f4ce06]

-   Updated dependencies [39ab15616]

-   Updated dependencies [c1ab2b340]

-   Updated dependencies [99a1f0ae6]

-   Updated dependencies [edf14d066]

-   Updated dependencies [2b68513be]

-   Updated dependencies [6be41b668]

-   Updated dependencies [374f383ba]

-   Updated dependencies [c050f2242]
    -   @comet/admin-theme@7.1.0
    -   @comet/admin@7.1.0
    -   @comet/blocks-admin@7.1.0
    -   @comet/admin-icons@7.1.0
    -   @comet/admin-date-time@7.1.0
    -   @comet/admin-rte@7.1.0

## @comet/cms-api@7.1.0

### Minor Changes

-   19d53c407: Add Sentry module to simplify integration with Sentry.

    ### Usage:

    ```ts
    // main.ts

    app.use(Sentry.Handlers.requestHandler());
    app.use(Sentry.Handlers.tracingHandler());
    app.use(Sentry.Handlers.errorHandler());
    ```

    ```ts
    // app.module.ts

    SentryModule.forRootAsync({
        dsn: "sentry_dsn_url",
        environment: "dev",
        shouldReportException: (exception) => {
// Custom logic to determine if the exception should be reported
            return true;
        },
    }),
    ```

### Patch Changes

- 87f74d307: Sort the keys in content scopes returned by
`UserPermissionsService` alphabetically

This fixes issues when comparing content scopes after converting them to
strings via `JSON.stringify()`.

    This specifically fixes a bug on the UserPermissionsPage:
When the `availableContentScopes` passed to the `UserPermissionsModule`
weren't sorted alphabetically, the allowed scopes wouldn't be displayed
correctly in the UI.

    -   @comet/blocks-api@7.1.0

## @comet/cms-site@7.1.0

### Minor Changes

-   7ad7a50a6: PixelImageBlock: Set `object-fit` to `cover` per default

When setting `object-fit` to `cover`, the image will fill the container
and maintain its aspect ratio.
    This is the most common use case for images in our applications.
The default behavior for `object-fit` (which is `fill`) resulted in
distorted images.

This behavior can be overridden by setting the `style` prop on the
`PixelImageBlock` component, which is forwarded to the `next/image`
component:

    ```diff
    <PixelImageBlock
      ...
      fill
    + style={{ objectFit: "contain" }}
    />
    ```

## @comet/admin-color-picker@7.1.0

### Patch Changes

-   Updated dependencies [04844d39e]
-   Updated dependencies [dfc4a7fff]
-   Updated dependencies [b1bbd6a0c]
-   Updated dependencies [c0488eb84]
-   Updated dependencies [39ab15616]
-   Updated dependencies [c1ab2b340]
-   Updated dependencies [99a1f0ae6]
-   Updated dependencies [edf14d066]
-   Updated dependencies [2b68513be]
-   Updated dependencies [374f383ba]
-   Updated dependencies [c050f2242]
    -   @comet/admin@7.1.0
    -   @comet/admin-icons@7.1.0

## @comet/admin-date-time@7.1.0

### Patch Changes

-   Updated dependencies [04844d39e]
-   Updated dependencies [dfc4a7fff]
-   Updated dependencies [b1bbd6a0c]
-   Updated dependencies [c0488eb84]
-   Updated dependencies [39ab15616]
-   Updated dependencies [c1ab2b340]
-   Updated dependencies [99a1f0ae6]
-   Updated dependencies [edf14d066]
-   Updated dependencies [2b68513be]
-   Updated dependencies [374f383ba]
-   Updated dependencies [c050f2242]
    -   @comet/admin@7.1.0
    -   @comet/admin-icons@7.1.0

## @comet/admin-react-select@7.1.0

### Patch Changes

-   Updated dependencies [04844d39e]
-   Updated dependencies [dfc4a7fff]
-   Updated dependencies [b1bbd6a0c]
-   Updated dependencies [c0488eb84]
-   Updated dependencies [39ab15616]
-   Updated dependencies [c1ab2b340]
-   Updated dependencies [99a1f0ae6]
-   Updated dependencies [edf14d066]
-   Updated dependencies [2b68513be]
-   Updated dependencies [374f383ba]
-   Updated dependencies [c050f2242]
    -   @comet/admin@7.1.0
    -   @comet/admin-icons@7.1.0

## @comet/admin-rte@7.1.0

### Patch Changes

-   Updated dependencies [04844d39e]
-   Updated dependencies [dfc4a7fff]
-   Updated dependencies [b1bbd6a0c]
-   Updated dependencies [c0488eb84]
-   Updated dependencies [39ab15616]
-   Updated dependencies [c1ab2b340]
-   Updated dependencies [99a1f0ae6]
-   Updated dependencies [edf14d066]
-   Updated dependencies [2b68513be]
-   Updated dependencies [374f383ba]
-   Updated dependencies [c050f2242]
    -   @comet/admin@7.1.0
    -   @comet/admin-icons@7.1.0

## @comet/eslint-config@7.1.0

### Patch Changes

-   @comet/eslint-plugin@7.1.0

## @comet/admin-babel-preset@7.1.0



## @comet/blocks-api@7.1.0



## @comet/cli@7.1.0



## @comet/eslint-plugin@7.1.0

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>